name: Publish to npm

on:
 push:
  tags:
   - 'v*'
 pull_request:

jobs:
 test:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v4
   - name: Install Node.js
     uses: actions/setup-node@v4
     with:
      node-version: 20
   - uses: pnpm/action-setup@v3
     name: Install pnpm
     with:
      version: 8
      run_install: false
   - name: Get pnpm store directory
     shell: bash
     run: |
      echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
   - uses: actions/cache@v4
     name: Setup pnpm cache
     with:
      path: ${{ env.STORE_PATH }}
      key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
      restore-keys: |
       ${{ runner.os }}-pnpm-store-
   - name: Install dependencies
     run: pnpm install
   - name: Run tests
     run: pnpm test

 publish:
  needs: test
  runs-on: ubuntu-latest
  if: startsWith(github.ref, 'refs/tags/v')
  steps:
   - name: Checkout
     uses: actions/checkout@v4
   - name: Install Node.js
     uses: actions/setup-node@v4
     with:
      node-version: 20
      registry-url: 'https://registry.npmjs.org'
   - uses: pnpm/action-setup@v3
     name: Install pnpm
     with:
      version: 8
      run_install: false
   - name: Get pnpm store directory
     shell: bash
     run: |
      echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
   - uses: actions/cache@v4
     name: Setup pnpm cache
     with:
      path: ${{ env.STORE_PATH }}
      key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
      restore-keys: |
       ${{ runner.os }}-pnpm-store-
   - name: Install dependencies
     run: pnpm install
   - name: Build project
     run: pnpm run build
   - name: Publish to npm
     run: pnpm publish
     env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
